/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as IndexRouteImport } from './routes/index'

const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shops': typeof ShopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shops': typeof ShopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shops': typeof ShopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shops'
  id: '__root__' | '/' | '/shops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopsRoute: typeof ShopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopsRoute: ShopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
