/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as AdminShopsIndexRouteImport } from './routes/admin.shops.index'
import { Route as AdminShopsNewRouteImport } from './routes/admin.shops.new'
import { Route as AdminShopsSlugEditRouteImport } from './routes/admin.shops.$slug.edit'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsIndexRoute = AdminShopsIndexRouteImport.update({
  id: '/admin/shops/',
  path: '/admin/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsNewRoute = AdminShopsNewRouteImport.update({
  id: '/admin/shops/new',
  path: '/admin/shops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsSlugEditRoute = AdminShopsSlugEditRouteImport.update({
  id: '/admin/shops/$slug/edit',
  path: '/admin/shops/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/shops/': typeof ShopsIndexRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/admin/shops/$slug/edit': typeof AdminShopsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/shops': typeof ShopsIndexRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/shops': typeof AdminShopsIndexRoute
  '/admin/shops/$slug/edit': typeof AdminShopsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/shops/': typeof ShopsIndexRoute
  '/admin/shops/new': typeof AdminShopsNewRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/admin/shops/$slug/edit': typeof AdminShopsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/shops/$slug'
    | '/shops/'
    | '/admin/shops/new'
    | '/admin/shops/'
    | '/admin/shops/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/shops/$slug'
    | '/shops'
    | '/admin/shops/new'
    | '/admin/shops'
    | '/admin/shops/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/shops/$slug'
    | '/shops/'
    | '/admin/shops/new'
    | '/admin/shops/'
    | '/admin/shops/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  AdminShopsNewRoute: typeof AdminShopsNewRoute
  AdminShopsIndexRoute: typeof AdminShopsIndexRoute
  AdminShopsSlugEditRoute: typeof AdminShopsSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops/': {
      id: '/admin/shops/'
      path: '/admin/shops'
      fullPath: '/admin/shops/'
      preLoaderRoute: typeof AdminShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops/new': {
      id: '/admin/shops/new'
      path: '/admin/shops/new'
      fullPath: '/admin/shops/new'
      preLoaderRoute: typeof AdminShopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops/$slug/edit': {
      id: '/admin/shops/$slug/edit'
      path: '/admin/shops/$slug/edit'
      fullPath: '/admin/shops/$slug/edit'
      preLoaderRoute: typeof AdminShopsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ShopsSlugRoute: ShopsSlugRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  AdminShopsNewRoute: AdminShopsNewRoute,
  AdminShopsIndexRoute: AdminShopsIndexRoute,
  AdminShopsSlugEditRoute: AdminShopsSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
